package(default_visibility = ["//visibility:public"])

java_library(
    name = "graphoenix-antlr",
    srcs = glob(["src/main/java/graphql/parser/antlr/*.java", "src/main/java/io/graphoenix/antlr/manager/*.java"]),
    deps = ["@maven//:org_antlr_antlr4_runtime"],
)

